
name: CI

on:
  push:
    paths:
      - _data/navigation.yml
    branches: [ main ]
  pull_request:
    paths:
      - _data/navigation.yml
    branches: [ main ]
jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0
      - name: Install broken packges
        run: |
          sudo apt-get install texlive
      - name: Generate pdf from LaTex 
        uses: docker://pandoc/latex:2.11.4
        with:
          args: " --pdf-engine=xelatex --template=_data/template.tex -o assets/cv.pdf _data/navigation.yml"
      - name: Commit changed files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/cv.pdf
          git commit -m "Update pdf"
      - name: Push new changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
